use std::path::Path;

const CONFIG_TEMPLATE: &str = r#"# Atlas LLM Configuration
# Generated by `atlas init`. Edit before running `atlas index`.
#
# Model strings use the format: <provider>/<model-id>
# Supported providers:
#   claude-code  — Anthropic Claude Code CLI subprocess (requires `claude` on PATH)
#   codex        — OpenAI Codex CLI subprocess (stub; pending research task)
#   anthropic    — Anthropic Messages HTTP API (requires ANTHROPIC_API_KEY)
#   openai       — OpenAI Chat Completions HTTP API (requires OPENAI_API_KEY)
#
# API keys use ${ENV_VAR} interpolation and are resolved at startup.
# Never hardcode secrets here — this file is safe to commit as long as
# the referenced env vars are kept out of version control.

# Credentials for HTTP providers. Only providers referenced in
# defaults/operations below need entries here.
# providers:
#   anthropic:
#     api_key: ${ANTHROPIC_API_KEY}
#   openai:
#     api_key: ${OPENAI_API_KEY}

# Global defaults — `model` is REQUIRED. `params.max_tokens` is required
# whenever the resolved provider is HTTP (`anthropic`, `openai`); ignored
# for subprocess providers (`claude-code`, `codex`). Shipped active so a
# user flipping `model:` to an HTTP provider only needs to add the api_key.
# 4096 fits Haiku/Sonnet-class outputs; raise to 8192+ for Opus/larger.
defaults:
  model: claude-code/claude-sonnet-4-6
  params:
    max_tokens: 4096

# Per-operation overrides — all optional; absent entries inherit `defaults`
# (including `params.max_tokens`). Override `max_tokens` per-op when a
# specific stage needs a different output budget.
# operations:
#
#   # L3: is_component — one call per candidate directory.
#   # Fast models work well here; inputs are bounded manifest snippets.
#   classify:
#     model: anthropic/claude-haiku-4-5
#     params:
#       max_tokens: 1024
#
#   # L8: subcarve decision — one call per immediate subdirectory.
#   subcarve:
#     model: anthropic/claude-haiku-4-5
#     params:
#       max_tokens: 512
#
#   # L5: surface extraction — reads source files; keep agentic.
#   surface:
#     model: claude-code/claude-sonnet-4-6
#
#   # L6: edge synthesis — cross-component; keep agentic and broadly contextual.
#   edges:
#     model: claude-code/claude-opus-4-7
"#;

const COMPONENTS_OVERRIDES_TEMPLATE: &str = r#"# components.overrides.yaml
# Pin, suppress, or add components to override Atlas's automatic classification.
# Changes here persist across re-runs; Atlas never overwrites this file.

schema_version: 1

# --- Pin a component field ---
# pins:
#   my-lib:
#     kind: rust-library       # fix kind so LLM cannot change it
#   tools/build:
#     suppress: true           # exclude this component entirely
#
# --- Add a component Atlas missed ---
# additions:
# - id: custom-scripts
#   path: scripts/custom
#   kind: tooling
#   role: "Build and release scripts"
"#;

const SUBSYSTEMS_OVERRIDES_TEMPLATE: &str = r#"# subsystems.overrides.yaml
# Group components into named subsystems. Produced as subsystems.yaml
# after `atlas index`.
#
# Membership forms:
#   - Glob (contains / or *): matches component paths
#   - Id (no / or *): matches exact component ids

schema_version: 1

# subsystems:
# - id: auth
#   role: "Authentication and authorisation boundary"
#   members:
#   - services/auth/*       # glob — all components under services/auth/
#   - auth-shared           # id   — exact component id
"#;

pub fn run_init_cmd(root: &Path) -> anyhow::Result<std::process::ExitCode> {
    let atlas_dir = root.join(".atlas");
    std::fs::create_dir_all(&atlas_dir)?;

    write_template(&atlas_dir.join("config.yaml"), CONFIG_TEMPLATE)?;
    write_template(
        &atlas_dir.join("components.overrides.yaml"),
        COMPONENTS_OVERRIDES_TEMPLATE,
    )?;
    write_template(
        &atlas_dir.join("subsystems.overrides.yaml"),
        SUBSYSTEMS_OVERRIDES_TEMPLATE,
    )?;

    Ok(std::process::ExitCode::SUCCESS)
}

fn write_template(path: &Path, content: &str) -> anyhow::Result<()> {
    if path.exists() {
        println!("skipped {} (already exists)", path.display());
        return Ok(());
    }
    std::fs::write(path, content)?;
    println!("written {}", path.display());
    Ok(())
}
