//! Generates per-template token-list constants from the shipped prompt
//! files at build time. The generated file is `include!`'d by
//! `prompt_token_coverage.rs`, which uses the constants for compile-time
//! bidirectional validation against each layer's `BUILD_INPUTS_KEYS`
//! declaration.
//!
//! Forward direction (every `{{TOKEN}}` has a matching builder key) and
//! inverse direction (every builder key has a matching `{{TOKEN}}` or
//! is declared cache-only) are both enforced at compile time once the
//! generated tokens are compared against each layer's `const`-declared
//! key list — see `prompt_token_coverage.rs`.

use std::env;
use std::fs;
use std::path::PathBuf;

/// Templates participating in the bidirectional coverage check.
///
/// `subcarve.md` is intentionally absent: as of the L8 map/reduce
/// redesign the engine no longer renders it (the per-subdir map step
/// routes through `Classify`). The file remains in `EMBEDDED_PROMPTS`
/// for fingerprint stability but is not a live prompt.
const TEMPLATES: &[(&str, &str)] = &[
    ("CLASSIFY_TEMPLATE_TOKENS", "defaults/prompts/classify.md"),
    (
        "STAGE1_SURFACE_TEMPLATE_TOKENS",
        "defaults/prompts/stage1-surface.md",
    ),
    (
        "STAGE2_EDGES_TEMPLATE_TOKENS",
        "defaults/prompts/stage2-edges.md",
    ),
];

fn main() {
    let manifest_dir = PathBuf::from(env::var_os("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    // crates/atlas-engine -> ../../  is workspace root
    let workspace_root = manifest_dir
        .parent()
        .and_then(|p| p.parent())
        .expect("atlas-engine lives at <workspace>/crates/atlas-engine")
        .to_path_buf();

    let out_dir = PathBuf::from(env::var_os("OUT_DIR").expect("OUT_DIR"));

    let mut generated = String::from(
        "// Generated by atlas-engine/build.rs from defaults/prompts/.\n\
         // Edit the templates, not this file.\n\n",
    );

    for (const_name, rel_path) in TEMPLATES {
        let abs_path = workspace_root.join(rel_path);
        // Path is relative to crates/atlas-engine/Cargo.toml per cargo's
        // resolution rules for `cargo:rerun-if-changed`.
        println!("cargo:rerun-if-changed=../../{rel_path}");
        let template = fs::read_to_string(&abs_path)
            .unwrap_or_else(|e| panic!("failed to read {}: {e}", abs_path.display()));
        let tokens = collect_template_tokens(&template, rel_path);
        generated.push_str(&format!("pub(crate) const {const_name}: &[&str] = &[\n"));
        for token in &tokens {
            generated.push_str(&format!("    {token:?},\n"));
        }
        generated.push_str("];\n\n");
    }

    let dest = out_dir.join("prompt_token_coverage_generated.rs");
    fs::write(&dest, generated)
        .unwrap_or_else(|e| panic!("failed to write {}: {e}", dest.display()));
}

/// Extract every distinct `{{TOKEN}}` name referenced in `template`,
/// using the same grammar as `atlas_llm::prompt::render`: `{{TOKEN}}`
/// substitutes, `{{{{` and `}}}}` are literal-brace escapes. The result
/// preserves first-appearance order so the generated file is stable.
fn collect_template_tokens(template: &str, label: &str) -> Vec<String> {
    let mut tokens: Vec<String> = Vec::new();
    let mut rest = template;
    while !rest.is_empty() {
        if let Some(body) = rest.strip_prefix("{{{{") {
            rest = body;
            continue;
        }
        if let Some(body) = rest.strip_prefix("}}}}") {
            rest = body;
            continue;
        }
        if let Some(body) = rest.strip_prefix("{{") {
            let end = body
                .find("}}")
                .unwrap_or_else(|| panic!("unclosed `{{{{` in template `{label}`"));
            let name = body[..end].trim().to_string();
            if !tokens.contains(&name) {
                tokens.push(name);
            }
            rest = &body[end + 2..];
            continue;
        }
        let ch = rest.chars().next().unwrap();
        rest = &rest[ch.len_utf8()..];
    }
    tokens
}
